# Generated by Django 3.2.25 on 2026-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberbullying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='isbullyingpost',
            field=models.BooleanField(default=False),
        ),
    ]
